---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: deps
  become: yes
  become_user: root
  package: name={{item}} state=present
  with_items: '{{couchdb_dep_pkgs}}'

- name: create couchdb group
  become: yes
  become_user: root
  group: name={{couchdb_group}} state=present
  
- name: create couchdb user
  become: yes
  become_user: root
  user: >-
    name={{couchdb_user}}
    group={{couchdb_group}}
    home={{couchdb_home_dir}}
    state=present

- name: download...
  become: yes
  become_user: '{{couchdb_user}}'
  get_url: >-
    url={{couchdb_url}}
    dest=/tmp/{{couchdb_tgz}}
    mode=0644

- name: unarchive...
  become: yes
  become_user: '{{couchdb_user}}'
  unarchive: >-
    copy=no
    src=/tmp/{{couchdb_tgz}}
    dest={{couchdb_src_dir}}
    creates={{couchdb_src_dir}}/{{couchdb_name}}

- name: configure build...
  become: yes
  become_user: '{{couchdb_user}}'
  command: ./configure
  args:
    chdir: '{{couchdb_src_dir}}'
    creates: '{{couchdb_src_dir}}/rel/couchdb.config'
    
- name: build...
  become: yes
  become_user: '{{couchdb_user}}'
  command: make release
  args:
    chdir: '{{couchdb_src_dir}}'
    creates: '{{couchdb_src_dir}}/rel/couchdb'

- name: install...
  become: yes
  become_user: root
  command: cp -R {{couchdb_src_dir}}/rel/couchdb/* {{couchdb_home_dir}}
  args:
    creates: '{{couchdb_home_dir}}/bin/couchdb'


