---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: deps
  become: yes
  become_user: root
  package: name={{item}} state=present
  with_items: '{{couchdb_dep_pkgs}}'

- name: download...
  become: yes
  become_user: root
  get_url: >-
    url={{couchdb_url}}
    dest=/tmp/{{couchdb_tgz}}
    mode=0644

- name: unarchive...
  become: yes
  become_user: root
  unarchive: >-
    copy=no
    src=/tmp/{{couchdb_tgz}}
    dest=/opt
    creates=/opt/{{couchdb_name}}

- name: configure build...
  become: yes
  become_user: root
  command: ./configure
  args:
    chdir: /opt/{{couchdb_name}}
    creates: /opt/{{couchdb_name}}/rel/couchdb.config
    
- name: build...
  become: yes
  become_user: root
  command: make release
  args:
    chdir: /opt/{{couchdb_name}}
    creates: /opt/{{couchdb_name}}/rel/couchdb

- name: install...
  become: yes
  become_user: root
  command: cp -R /opt/{{couchdb_name}}/rel/couchdb {{couchdb_install_parent_dir}}/{{couchdb_name}}
  args:
    creates: '{{couchdb_install_parent_dir}}/{{couchdb_name}}'

- name: link...
  become: yes
  become_user: root
  file: >-
    src={{couchdb_install_parent_dir}}/{{couchdb_name}}
    dest={{couchdb_install_parent_dir}}/couchdb
    state=link

