---
- name: add the couchdb user group
  group: name=couchdb state=present
  
- name: add the couchdb user
  user: >
    name=couchdb
    group=couchdb
    home=/var/lib/couchdb
    state=present

- name: deps
  when: ansible_os_family == 'Debian'
  package: name={{item}} state=present
  with_items:
    - ca-certificates
    - curl
    - erlang-nox
    - libicu52
    - libmozjs185-1.0
    - libnspr4
    - libnspr4-0d
    - gcc
    - g++
    - erlang-dev
    - libcurl4-openssl-dev
    - libicu-dev
    - libmozjs185-dev
    - libnspr4-dev
    - make

- name: download...
  command: curl -s -L {{couchdb_url}} -o /tmp/{{couchdb_tgz}}
  args:
    creates: /tmp/{{couchdb_tgz}}
    
- name: perms of tgz
  file: >-
    path=/tmp/{{couchdb_tgz}}
    owner=root
    group=root
    mode=644

- name: ensure existence of /opt
  file: >-
    path=/opt
    owner=root
    group=root
    mode=0755
    state=directory
    
- name: unarchive...
  unarchive: >-
    copy=no
    src=/tmp/{{couchdb_tgz}}
    dest=/opt
    creates=/opt/{{couchdb_name}}

- name: build it...
  command: '{{item}}'
  args:
    chdir: /opt/{{couchdb_name}}
  with_items:
    - ./configure --with-js-lib=/usr/lib --with-js-include=/usr/include/mozjs
    - make
    - make install
    
