---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: deps
  become: yes
  become_user: root
  package: name={{item}} state=present
  with_items: '{{couchdb_dep_pkgs}}'

- name: download...
  become: yes
  become_user: root
  get_url: >-
    url={{couchdb_url}}
    dest=/tmp/{{couchdb_tgz}}

- name: unarchive...
  become: yes
  become_user: root
  unarchive: >-
    copy=no
    src=/tmp/{{couchdb_tgz}}
    dest=/opt
    creates=/opt/{{couchdb_name}}

- name: configure build...
  become: yes
  become_user: root
  command: ./configure --with-js-lib=/usr/lib --with-js-include=/usr/include/mozjs
  args:
    chdir: /opt/{{couchdb_name}}
    creates: /opt/{{couchdb_name}}/Makefile
    
- name: build/install...
  become: yes
  become_user: root
  shell: make && make install
  args:
    chdir: /opt/{{couchdb_name}}
    creates: /usr/local/bin/couchdb
    
- name: configure install....
  become: yes
  become_user: root
  with_items:
    - httpd_proxies.ini
    - httpd.ini
    - admins.ini
  template: >-
    src={{item}}.j2
    dest=/usr/local/etc/couchdb/local.d/{{item}}
    mode=0644
  
