---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: deps
  package: name={{item}} state=present
  with_items: '{{couchdb_dep_pkgs}}'

- name: download...
  command: curl -s -L {{couchdb_url}} -o /tmp/{{couchdb_tgz}}
  args:
    creates: /tmp/{{couchdb_tgz}}

- name: fix perms
  file: >
    path=/tmp/{{couchdb_tgz}}
    owner=root
    group=root
    mode=644

- name: unarchive...
  unarchive: >-
    copy=no
    src=/tmp/{{couchdb_tgz}}
    dest=/opt
    creates=/opt/{{couchdb_name}}

- name: configure build...
  command: ./configure --with-js-lib=/usr/lib --with-js-include=/usr/include/mozjs
  args:
    chdir: /opt/{{couchdb_name}}
    creates: /opt/{{couchdb_name}}/Makefile
    
- name: build/install...
  shell: make && make install
  args:
    chdir: /opt/{{couchdb_name}}
    creates: /usr/local/bin/couchdb
    
- name: configure install....
  template: >-
    src={{item}}.j2
    dest=/usr/local/etc/couchdb/local.d/{{item}}
    owner=root
    group=root
    mode=0644
  with_items:
    - httpd_proxies.ini
    - httpd.ini
    - admins.ini
  
