---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_os_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: deps
  package: name={{item}} state=present
  with_items: '{{couchdb_dep_pkgs}}'

- name: download...
  get_url: >
    url={{couchdb_url}}
    dest=/tmp/{{couchdb_tgz}}
    owner=root
    group=root
    mode=644

- name: unarchive...
  unarchive: >-
    copy=no
    src=/tmp/{{couchdb_tgz}}
    dest=/opt
    creates=/opt/{{couchdb_name}}

- name: build it...
  command: '{{item}}'
  args:
    chdir: /opt/{{couchdb_name}}
  with_items:
    - ./configure --with-js-lib=/usr/lib --with-js-include=/usr/include/mozjs
    - make
    - make install
    
